# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage:'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: |
      git clone https://github.com/XXX/XXX.git
      git config --global user.name "jfadiga@nodefusion.com"
      git checkout master
      git add .
      git commit -m "abc"
      git push https://{AzureDevopsPAT}@dev.azure.com/3pro-pilot1/SetVersionTest/_git/delete.git